version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: tasky_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tasky_db
      POSTGRES_USER: tasky_user
      POSTGRES_PASSWORD: tasky_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: tasky_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
